name: 'Automatic version updates'
on:
  schedule:
    # minute hour dom month dow (UTC)
    - cron: '0 16 * * *'
jobs:
  version_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: wader/bump/action@master
        env:
          GITHUB_TOKEN: ${{ secrets.BUMP_TOKEN }}
