name: CI

on:
  pull_request:
    branches:
      - 'master'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
